#!/usr/bin/env python3
"""
Deploy a fresh LTMigrator (with the limit=1 fallback fix — see b137702)
and create a YB DAO vote that registers it as a limit setter on
HybridFactoryOwner while disabling PREVIOUS_LT_MIGRATOR — the build that
deploy_yb_pools_v3.py Vote 1 (https://yieldbasis.com/proposal/37)
installs, whose lt_allocate_stablecoins(lt_from, 0) call reverts after a
HybridVault withdrawal flips disabled_lts back to False on a deprecated
LT.

Both the enable and the disable happen as actions inside a single DAO
proposal so the swap is atomic.

Usage:
  python scripts/voting/create_vote_swap_migrator.py          # production
  python scripts/voting/create_vote_swap_migrator.py --test   # forked dry-run

--test forks mainnet-cluster at head, pushes the 6 pending
deploy_yb_pools_v3 votes through (so PREVIOUS_LT_MIGRATOR becomes the
registered one), deploys the new migrator locally, creates this swap
proposal, passes + executes it via the test whales, and asserts the
limit_setters mapping flipped as expected.
"""
import json
import os
import sys
import urllib.request
from collections import namedtuple
from getpass import getpass
from time import sleep

import boa
import requests
from eth_account import account
from eth_utils import keccak, to_checksum_address

from boa.explorer import Etherscan
from boa.verifiers import verify as boa_verify

from networks import NETWORK, PINATA_TOKEN, ETHERSCAN_API_KEY

VOTING_PLUGIN = "0x2be6670DE1cCEC715bDBBa2e3A6C1A05E496ec78"
YB_FACTORY = "0x370a449FeBb9411c95bf897021377fe0B7D100c0"

# The LTMigrator this script disables. Deployed by the deploy_yb_pools_v3.py
# production run and registered as limit_setter by YB DAO Vote 1
# (https://yieldbasis.com/proposal/37). Has the legacy
# lt_allocate_stablecoins(lt_from, 0) call that reverts when a HybridVault
# withdrawal flips HybridFactoryOwner.disabled_lts[lt_from] back to False.
PREVIOUS_LT_MIGRATOR = "0xDfD6fe3A540F68601002E889E33117a7E8A0669D"

# Brownie keystore for the proposer EOA. TokenVoting enforces a 1-day
# per-address createProposal cooldown, so this needs to be an account
# whose last Aragon proposal is at least 24h old.
PROPOSER_KEYSTORE = "yb-deployer"

# The 6 deploy_yb_pools_v3.py proposers, in vote-creation order. Used in
# --test to scope discovery to those proposals (and force-execute them so
# PREVIOUS_LT_MIGRATOR becomes a registered limit_setter on the fork).
DEPLOY_PROPOSERS = [
    "yb-deployer", "yb-deployer-a", "yb-deployer-b", "yb-deployer-c",
    "yb-deployer-2", "yb-deployer-3",
]

# Largest veYB voters — forked dry-run only. Generated by
# scripts/voting/find_ve_voters.py (top 25, ~75% of veYB power).
TEST_VOTERS = [
    "0xD10782f4D4fE20f5E15f3347E5D59aB3eC6D63d6",
    "0xb75BB762e5D62ca8f23FAbC87b1f651d0171d521",
    "0x0070D9adC687a28FBAcC0a0Aab24B90c037AD24e",
    "0x0000000C90799449af8eE0B240Da639144a36C6A",
    "0x29B6a3512FafeAce91433D278503ABC3D5aB5d12",
    "0x64A0f7Ca6efbFDaF975B5127650EC9f175182d7b",
    "0x2DE99955fA0318556f3542E71421EFD1BCF3293a",
    "0xc64566f526F09eEeFbd284760D0E1b94c6e69fc8",
    "0xb373e9C6D3Ad91eD03AA4b3C8106e68Bf3de192f",
    "0xC2059e0F6C4c1D441BAf295BC6Ea15cE24c71701",
    "0x2029Df02833eb9cd83A5143AbfE5d65BC4B46A16",
    "0xEeee8f503bCF020bc0909D35FBAbEe9ffD24641a",
    "0xaE922Cea2323fD75a31e28d10E0c84F49e1Fb6b7",
    "0xc900C3EFDC7d790f50b0B43b0c4206F8141a77eC",
    "0x52658B966801D8ddB6f49c886557084EC459Aa27",
    "0x53F8Ef5B139824C85d3f837C6b535470bFBFEeE3",
    "0xfF642740228d6abe9786612A421C0B1b859f0793",
    "0x0ca0e5c9f426d1e3EF1f568862716c68b1f44a01",
    "0x9cB95F0Fa3dB70eb15D1505d3c73a55766A1Ec89",
    "0x387ACB7f56A6f29137a21d7Eb755A3F638cab45B",
    "0x3340a1541296E7A4db2Ac6f9C3776bda7eF62724",
    "0xF791da446D04282f921f38FBF954aD5cAee899a3",
    "0x27c6DCcF18d6e66942dc5a250B1618B6B3A44036",
    "0x858a2FEf6C0833f8a5532122bb964655b0E6d5B5",
    "0x1105c075A4034C57d1457151b2D7cAb2ed99B122",
]

VOTE_YES = 2
LOG_CHUNK = 10_000
VERIFY_RETRY_SECONDS = 10
PROPOSAL_CREATED_TOPIC0 = "0x" + keccak(
    text="ProposalCreated(uint256,address,uint64,uint64,bytes,"
         "(address,uint256,bytes)[],uint256)"
).hex()

Proposal = namedtuple(
    "Proposal",
    ["metadata", "actions", "allowFailureMap", "startDate", "endDate",
     "voteOption", "tryEarlyExecution"],
)
Action = namedtuple("Action", ["to", "value", "data"])
ABI_DIR = os.path.dirname(os.path.abspath(__file__))


# --- RPC + keystore helpers --------------------------------------------------

def _rpc(method, params):
    req = urllib.request.Request(
        NETWORK,
        data=json.dumps(
            {"jsonrpc": "2.0", "id": 1, "method": method, "params": params}
        ).encode(),
        headers={"Content-Type": "application/json"},
    )
    r = json.loads(urllib.request.urlopen(req, timeout=120).read())
    if r.get("error"):
        raise RuntimeError(f"RPC {method}: {r['error']}")
    return r["result"]


def _keystore_path(name: str) -> str:
    return os.path.expanduser(
        os.path.join("~", ".brownie", "accounts", name + ".json"))


def keystore_address(name: str) -> str:
    with open(_keystore_path(name)) as f:
        return to_checksum_address("0x" + json.load(f)["address"])


def account_load(name: str):
    with open(_keystore_path(name)) as f:
        pkey = account.decode_keyfile_json(json.load(f), getpass())
    return account.Account.from_key(pkey)


# --- contract handles --------------------------------------------------------

def load_contracts():
    factory = boa.load_partial("contracts/Factory.vy").at(YB_FACTORY)
    factory_owner = boa.load_partial("contracts/HybridFactoryOwner.vy").at(
        factory.admin())
    voting = boa.load_abi(
        os.path.join(ABI_DIR, "TokenVoting.abi.json"), name="AragonVoting"
    ).at(VOTING_PLUGIN)
    ve = boa.load_partial("contracts/dao/VotingEscrow.vy").at(
        voting.getVotingToken())
    return factory, factory_owner, voting, ve


# --- forked-test: passing + executing pending votes --------------------------

def _scan_deploy_votes(latest_block: int) -> list[int]:
    """deploy_yb_pools_v3.py proposal ids in creation order, filtered by
    creator so unrelated pending proposals don't sneak in."""
    creators = {keystore_address(n).lower() for n in DEPLOY_PROPOSERS}
    seen = {}
    hi = latest_block
    while hi > 0 and len(seen) < len(DEPLOY_PROPOSERS):
        lo = max(hi - LOG_CHUNK + 1, 0)
        for log in _rpc("eth_getLogs", [{
            "address": VOTING_PLUGIN, "topics": [PROPOSAL_CREATED_TOPIC0],
            "fromBlock": hex(lo), "toBlock": hex(hi),
        }]):
            creator = "0x" + log["topics"][2][26:]
            if creator.lower() not in creators:
                continue
            seen[int(log["topics"][1], 16)] = int(log["blockNumber"], 16)
        hi = lo - 1
    return sorted(seen, key=lambda p: seen[p])


def pass_vote(voting, pid: int):
    cast = 0
    for voter in TEST_VOTERS:
        if voting.isMinParticipationReached(pid):
            break
        if not voting.canVote(pid, voter, VOTE_YES):
            continue
        with boa.env.prank(voter):
            voting.vote(pid, VOTE_YES, False)
        cast += 1
    if not voting.isMinParticipationReached(pid):
        raise RuntimeError(f"Proposal {pid} did not reach quorum "
                           f"({cast} whales voted)")
    print(f"    {cast} whale(s) voted YES; quorum reached")


def execute_pending(voting, proposal_ids: list[int]):
    pending = [pid for pid in proposal_ids if not voting.getProposal(pid)[1]]
    if not pending:
        return
    print(f"  voting on {len(pending)} pending proposal(s)...")
    for pid in pending:
        pass_vote(voting, pid)
    boa.env.time_travel(seconds=voting.minDuration() + 3600)
    for pid in pending:
        if voting.getProposal(pid)[1]:
            continue
        assert voting.canExecute(pid), f"proposal {pid} cannot execute"
        voting.execute(pid)


# --- the swap vote -----------------------------------------------------------

def build_vote_actions(factory_owner, new_migrator: str) -> list[Action]:
    return [
        Action(to=factory_owner.address, value=0,
               data=factory_owner.set_limit_setter.prepare_calldata(
                   new_migrator, True)),
        Action(to=factory_owner.address, value=0,
               data=factory_owner.set_limit_setter.prepare_calldata(
                   PREVIOUS_LT_MIGRATOR, False)),
    ]


def vote_metadata(new_migrator: str) -> dict:
    return {
        "title": "YB v3: swap LTMigrator (limit=1 fallback fix)",
        "summary": (
            f"Register the new LTMigrator {new_migrator} as a limit setter "
            "on HybridFactoryOwner and disable the previously-registered "
            f"LTMigrator {PREVIOUS_LT_MIGRATOR} (Vote installed via "
            "https://yieldbasis.com/proposal/37). The previous build's "
            "lt_allocate_stablecoins(lt_from, 0) deallocation reverts "
            "('Not disabled') after a HybridVault withdrawal flips "
            "disabled_lts back to False on a deprecated LT, trapping "
            "users mid-migration. The new build branches on disabled_lts "
            "and falls back to limit=1 in that case, leaving lt_from at "
            "the sentinel allocation=1 so migrate-back is refused."
        ),
        "resources": [],
    }


# --- IPFS / Etherscan --------------------------------------------------------

def pin_to_ipfs(content: dict) -> str:
    response = requests.post(
        "https://api.pinata.cloud/pinning/pinJSONToIPFS",
        json={"pinataContent": content,
              "pinataMetadata": {"name": "pinnie.json"},
              "pinataOptions": {"cidVersion": 1}},
        headers={"Authorization": f"Bearer {PINATA_TOKEN}",
                 "Content-Type": "application/json"},
        timeout=30,
    )
    assert 200 <= response.status_code < 400, response.text
    return "ipfs://" + response.json()["IpfsHash"]


def verify_on_etherscan(contract, etherscan):
    while True:
        try:
            sleep(VERIFY_RETRY_SECONDS)
            boa_verify(contract, etherscan, wait=True)
            return
        except ValueError as e:
            print(e)
            if "Already Verified" in str(e):
                return


# --- entrypoints -------------------------------------------------------------

def run_test():
    boa.fork(NETWORK, block_identifier="latest")
    latest_block = boa.env.evm.patch.block_number
    factory, factory_owner, voting, ve = load_contracts()

    print("=== Executing pending deploy_yb_pools_v3 votes on the fork ===")
    deploy_pids = _scan_deploy_votes(latest_block)
    if len(deploy_pids) != len(DEPLOY_PROPOSERS):
        raise RuntimeError(
            f"Expected {len(DEPLOY_PROPOSERS)} deploy proposals, "
            f"found {len(deploy_pids)}")
    execute_pending(voting, deploy_pids)
    assert factory_owner.limit_setters(PREVIOUS_LT_MIGRATOR), (
        f"{PREVIOUS_LT_MIGRATOR} is not a limit_setter after Vote 1 — "
        "hardcoded address is wrong?")
    print(f"  previous (buggy) migrator: {PREVIOUS_LT_MIGRATOR}")

    print("\n=== Deploying new LTMigrator ===")
    new_migrator = boa.load(
        "contracts/LTMigrator.vy", factory.STABLECOIN(),
        factory_owner.address)
    print(f"  new migrator: {new_migrator.address}")

    print("\n=== Checkpointing VotingEscrow ===")
    ve.checkpoint()

    proposer = keystore_address(PROPOSER_KEYSTORE)
    print(f"\n=== Creating the swap vote from {PROPOSER_KEYSTORE} "
          f"({proposer}) ===")
    actions = build_vote_actions(factory_owner, new_migrator.address)
    with boa.env.prank(proposer):
        pid = voting.createProposal(*Proposal(
            metadata=b"", actions=actions, allowFailureMap=0,
            startDate=0, endDate=0, voteOption=0, tryEarlyExecution=True))
    print(f"  created proposal {pid}")

    print("\n=== Passing and executing the swap vote ===")
    pass_vote(voting, pid)
    boa.env.time_travel(seconds=voting.minDuration() + 3600)
    assert voting.canExecute(pid), "swap vote cannot execute"
    voting.execute(pid)

    print("\n=== Post-execution state ===")
    new_is = factory_owner.limit_setters(new_migrator.address)
    prev_is = factory_owner.limit_setters(PREVIOUS_LT_MIGRATOR)
    print(f"  limit_setters[new  {new_migrator.address}] = {new_is}")
    print(f"  limit_setters[prev {PREVIOUS_LT_MIGRATOR}] = {prev_is}")
    assert new_is and not prev_is, "swap state mismatch"
    print("\nMigrator swap works end-to-end.")


def run_prod():
    boa.set_network_env(NETWORK)
    boa.env.add_account(account_load(PROPOSER_KEYSTORE), force_eoa=True)
    factory, factory_owner, voting, ve = load_contracts()

    etherscan = Etherscan(api_key=ETHERSCAN_API_KEY)
    print("=== Deploying new LTMigrator ===")
    new_migrator = boa.load(
        "contracts/LTMigrator.vy", factory.STABLECOIN(),
        factory_owner.address)
    print(f"  new migrator: {new_migrator.address}")

    print(f"\n=== Verifying {new_migrator.address} on Etherscan ===")
    verify_on_etherscan(new_migrator, etherscan)
    print("  verified")

    print("\n=== Checkpointing VotingEscrow ===")
    ve.checkpoint()

    print("=== Creating the swap vote ===")
    metadata = pin_to_ipfs(vote_metadata(new_migrator.address)).encode()
    pid = voting.createProposal(*Proposal(
        metadata=metadata,
        actions=build_vote_actions(factory_owner, new_migrator.address),
        allowFailureMap=0,
        startDate=0, endDate=0, voteOption=0, tryEarlyExecution=True))
    print(f"Created proposal: {pid}")


if __name__ == "__main__":
    if "--test" in sys.argv[1:]:
        run_test()
    else:
        run_prod()
