#!/usr/bin/env python3
"""
Create the YB DAO vote that registers the 4 new YB v3 market gauges
(LiquidityGauge == market.staker) on the GaugeController.

deploy_yb_pools_v3.py created 6 pending Aragon-OSx votes that create markets
7-10 (WBTC, cbBTC, tBTC, WETH) and their LiquidityGauges - but none of them
register those gauges on the GaugeController, so the new markets would receive
no YB emissions. This script creates a 7th vote that does the registration.

The gauge addresses are CREATE-deterministic and were computed/verified by
scripts/predict_gauges.py - they are hard-coded below. Because this vote is
created while the market votes are still pending (the gauges do not exist
yet), every add_gauge is guarded by a CallComparator.check_equal on the
gauge's LP_TOKEN(): a STATICCALL to a contract with no code returns empty
data, which the comparator decodes to 0, so the check reverts unless the gauge
actually EXISTS and is bound to the expected LT at execution time. The vote is
therefore safe to create now and can only execute once the markets exist.

Usage:
  python scripts/voting/create_vote_add_gauges_v3.py          # create the vote
  python scripts/voting/create_vote_add_gauges_v3.py --test   # forked dry-run

--test forks mainnet-cluster, executes the 6 pending votes through the voting
plugin (passed with veYB whale votes from find_ve_voters.py), then creates and
executes this vote and checks the 4 gauges land in the GaugeController.
"""
import json
import os
import sys
import urllib.request
from collections import namedtuple
from getpass import getpass

import boa
import requests
from eth_account import account
from eth_utils import keccak
from vyper.utils import method_id

from networks import NETWORK, PINATA_TOKEN

VOTING_PLUGIN = "0x2be6670DE1cCEC715bDBBa2e3A6C1A05E496ec78"
YB_DAO = "0x42F2A41A0D0e65A440813190880c8a65124895Fa"
YB_FACTORY = "0x370a449FeBb9411c95bf897021377fe0B7D100c0"
CALL_COMPARATOR = "0xd3BFa85dc668Aab38121bE12D69dd180301dec25"

# Test proposer (forked dry-run only): the voting plugin requires the proposer
# to hold veYB (minProposerVotingPower), so this must be a real veYB holder
# whose lock outlasts the test's time-travel. Picked from find_ve_voters.py -
# the largest holder, ~8.2M veYB. The production hot wallet is created
# separately - set PROD_PROPOSER_KEYSTORE to its brownie keystore name.
TEST_PROPOSER = "0xD10782f4D4fE20f5E15f3347E5D59aB3eC6D63d6"
PROD_PROPOSER_KEYSTORE = None

# The 4 new YB v3 market gauges (LiquidityGauge == market.staker) and their
# LTs. CREATE-deterministic - computed and verified by scripts/predict_gauges.py.
GAUGES = [
    {"label": "WBTC",  "market": 7,
     "gauge": "0xAa0b1d265F23972eafB7d088e963BD31403A58F5",
     "lt":    "0x651D4b8168488FA163D85304662E8278d4c55BAa"},
    {"label": "cbBTC", "market": 8,
     "gauge": "0xF8764cBcdb15a9E4c7CA1b0b8a578d9ebEEC1b6f",
     "lt":    "0x722FC3640BA007C3E9867CCdB0dCa59F2e2F29F9"},
    {"label": "tBTC",  "market": 9,
     "gauge": "0xe83D888FE3213DD3471DE0bC1957E0f94F038483",
     "lt":    "0x771F7290428d830ECd41E980745c327e507823Ec"},
    {"label": "WETH",  "market": 10,
     "gauge": "0xd829456FD63Ada7DE0657714A3A7A26DE403E3D8",
     "lt":    "0x2B9c9f3BdcEb5d8E36a4704F08a78Fca53343cEa"},
]

# Largest veYB voters - forked dry-run only, used to pass the pending DAO
# votes. Generated by scripts/voting/find_ve_voters.py (top 25, ~75% of power).
TEST_VOTERS = [
    "0xD10782f4D4fE20f5E15f3347E5D59aB3eC6D63d6",
    "0xb75BB762e5D62ca8f23FAbC87b1f651d0171d521",
    "0x0070D9adC687a28FBAcC0a0Aab24B90c037AD24e",
    "0x0000000C90799449af8eE0B240Da639144a36C6A",
    "0x29B6a3512FafeAce91433D278503ABC3D5aB5d12",
    "0x64A0f7Ca6efbFDaF975B5127650EC9f175182d7b",
    "0x2DE99955fA0318556f3542E71421EFD1BCF3293a",
    "0xc64566f526F09eEeFbd284760D0E1b94c6e69fc8",
    "0xb373e9C6D3Ad91eD03AA4b3C8106e68Bf3de192f",
    "0xC2059e0F6C4c1D441BAf295BC6Ea15cE24c71701",
    "0x2029Df02833eb9cd83A5143AbfE5d65BC4B46A16",
    "0xEeee8f503bCF020bc0909D35FBAbEe9ffD24641a",
    "0xaE922Cea2323fD75a31e28d10E0c84F49e1Fb6b7",
    "0xc900C3EFDC7d790f50b0B43b0c4206F8141a77eC",
    "0x52658B966801D8ddB6f49c886557084EC459Aa27",
    "0x53F8Ef5B139824C85d3f837C6b535470bFBFEeE3",
    "0xfF642740228d6abe9786612A421C0B1b859f0793",
    "0x0ca0e5c9f426d1e3EF1f568862716c68b1f44a01",
    "0x9cB95F0Fa3dB70eb15D1505d3c73a55766A1Ec89",
    "0x387ACB7f56A6f29137a21d7Eb755A3F638cab45B",
    "0x3340a1541296E7A4db2Ac6f9C3776bda7eF62724",
    "0xF791da446D04282f921f38FBF954aD5cAee899a3",
    "0x27c6DCcF18d6e66942dc5a250B1618B6B3A44036",
    "0x858a2FEf6C0833f8a5532122bb964655b0E6d5B5",
    "0x1105c075A4034C57d1457151b2D7cAb2ed99B122",
]

VOTE_YES = 2  # Aragon TokenVoting VoteOption: None=0, Abstain=1, Yes=2, No=3
LOG_CHUNK = 10_000
LP_TOKEN_SELECTOR = method_id("LP_TOKEN()")
PROPOSAL_CREATED_TOPIC0 = "0x" + keccak(
    text="ProposalCreated(uint256,address,uint64,uint64,bytes,"
         "(address,uint256,bytes)[],uint256)"
).hex()

Proposal = namedtuple(
    "Proposal",
    ["metadata", "actions", "allowFailureMap", "startDate", "endDate",
     "voteOption", "tryEarlyExecution"],
)
Action = namedtuple("Action", ["to", "value", "data"])
ABI_DIR = os.path.dirname(os.path.abspath(__file__))


# --- contract handles --------------------------------------------------------

def load_contracts():
    factory = boa.load_partial("contracts/Factory.vy").at(YB_FACTORY)
    comparator = boa.load_partial("contracts/dao/CallComparator.vy").at(
        CALL_COMPARATOR)
    gc = boa.load_partial("contracts/dao/GaugeController.vy").at(
        factory.gauge_controller())
    voting = boa.load_abi(
        os.path.join(ABI_DIR, "TokenVoting.abi.json"), name="AragonVoting"
    ).at(VOTING_PLUGIN)
    ve = boa.load_partial("contracts/dao/VotingEscrow.vy").at(
        voting.getVotingToken())
    assert gc.owner() == YB_DAO, f"GaugeController owner is {gc.owner()}"
    return factory, comparator, gc, voting, ve


# --- the vote ----------------------------------------------------------------

def build_vote_actions(comparator, gc) -> list[Action]:
    """4 CallComparator existence guards followed by 4 GaugeController.add_gauge
    calls. Each guard reverts unless the gauge exists and its LP_TOKEN() equals
    the expected LT, so the whole vote reverts atomically if any gauge is
    missing or sits at an unexpected address at execution time."""
    actions = [
        Action(to=comparator.address, value=0,
               data=comparator.check_equal.prepare_calldata(
                   g["gauge"], LP_TOKEN_SELECTOR, int(g["lt"], 16)))
        for g in GAUGES
    ]
    actions += [
        Action(to=gc.address, value=0,
               data=gc.add_gauge.prepare_calldata(g["gauge"]))
        for g in GAUGES
    ]
    return actions


def vote_metadata() -> dict:
    gauges = ", ".join(f"{g['label']} {g['gauge']}" for g in GAUGES)
    return {
        "title": "YB v3: register the 4 new market gauges on GaugeController",
        "summary": (
            "Register the LiquidityGauges of the 4 new YB v3 markets "
            f"({gauges}) on the GaugeController so they can receive YB "
            "emissions. Each add_gauge is guarded by a CallComparator check "
            "on the gauge's LP_TOKEN(), so the vote can only execute once the "
            "pending market votes have actually created the gauges."
        ),
        "resources": [],
    }


# --- voting-plugin helpers (forked test) -------------------------------------

def _rpc(method, params):
    req = urllib.request.Request(
        NETWORK,
        data=json.dumps(
            {"jsonrpc": "2.0", "id": 1, "method": method, "params": params}
        ).encode(),
        headers={"Content-Type": "application/json"},
    )
    r = json.loads(urllib.request.urlopen(req, timeout=120).read())
    if r.get("error"):
        raise RuntimeError(f"RPC {method}: {r['error']}")
    return r["result"]


def discover_pending_votes(latest_block: int) -> list[int]:
    """The 6 most-recently-created proposal ids, in creation order. TokenVoting
    proposal ids are hashes, so they are read from ProposalCreated logs;
    scanned backwards from the head, stopping once 6 are in hand."""
    seen = {}
    hi = latest_block
    while hi > 0 and len(seen) < 6:
        lo = max(hi - LOG_CHUNK + 1, 0)
        for log in _rpc("eth_getLogs", [{
            "address": VOTING_PLUGIN, "topics": [PROPOSAL_CREATED_TOPIC0],
            "fromBlock": hex(lo), "toBlock": hex(hi),
        }]):
            seen[int(log["topics"][1], 16)] = int(log["blockNumber"], 16)
        hi = lo - 1
    if len(seen) < 6:
        raise RuntimeError(f"Found only {len(seen)} ProposalCreated logs")
    return sorted(seen, key=lambda p: seen[p])[-6:]


def pass_vote(voting, pid: int):
    """Cast YES with the test whales until the proposal reaches minimum
    participation (support is 100% since every vote is YES)."""
    cast = 0
    for voter in TEST_VOTERS:
        if voting.isMinParticipationReached(pid):
            break
        if not voting.canVote(pid, voter, VOTE_YES):
            continue
        with boa.env.prank(voter):
            voting.vote(pid, VOTE_YES, False)
        cast += 1
    if not voting.isMinParticipationReached(pid):
        raise RuntimeError(f"Proposal {pid} did not reach quorum "
                           f"({cast} whales voted)")
    print(f"    {cast} whale(s) voted YES; quorum reached")


# --- IPFS / accounts (production) --------------------------------------------

def pin_to_ipfs(content: dict) -> str:
    response = requests.post(
        "https://api.pinata.cloud/pinning/pinJSONToIPFS",
        json={"pinataContent": content,
              "pinataMetadata": {"name": "pinnie.json"},
              "pinataOptions": {"cidVersion": 1}},
        headers={"Authorization": f"Bearer {PINATA_TOKEN}",
                 "Content-Type": "application/json"},
        timeout=30,
    )
    assert 200 <= response.status_code < 400, response.text
    return "ipfs://" + response.json()["IpfsHash"]


def account_load(name: str):
    path = os.path.expanduser(
        os.path.join("~", ".brownie", "accounts", name + ".json"))
    with open(path) as f:
        pkey = account.decode_keyfile_json(json.load(f), getpass())
    return account.Account.from_key(pkey)


# --- entrypoints -------------------------------------------------------------

def run_test():
    boa.fork(NETWORK)
    latest_block = boa.env.evm.patch.block_number
    factory, comparator, gc, voting, ve = load_contracts()

    # The guard must revert while the gauges still have no code.
    print("=== Negative test: comparator guard before gauges exist ===")
    g0 = GAUGES[0]
    try:
        comparator.check_equal(g0["gauge"], LP_TOKEN_SELECTOR,
                               int(g0["lt"], 16))
        raise AssertionError("Guard passed though the gauge does not exist!")
    except Exception as e:
        if "Guard passed" in str(e):
            raise
        print(f"  Correctly reverted: {e}")

    # Execute the 6 pending votes through the plugin.
    print("\n=== Executing the 6 pending votes via the plugin ===")
    pending = discover_pending_votes(latest_block)
    print(f"  pending proposal ids: {pending}")
    for i, pid in enumerate(pending, start=1):
        if voting.getProposal(pid)[1]:
            print(f"  Vote {i} already executed - skipping")
            continue
        print(f"  Vote {i} ({pid}): voting…")
        pass_vote(voting, pid)
    boa.env.time_travel(seconds=voting.minDuration() + 3600)
    for i, pid in enumerate(pending, start=1):
        if voting.getProposal(pid)[1]:
            continue
        assert voting.canExecute(pid), f"Vote {i} cannot execute"
        voting.execute(pid)
        print(f"  Vote {i} executed.")

    # Predicted gauges must now exist on-chain.
    print("\n=== Verifying gauges against the created markets ===")
    for g in GAUGES:
        on_chain = factory.markets(g["market"]).staker
        assert on_chain.lower() == g["gauge"].lower(), (
            f"{g['label']}: hard-coded {g['gauge']} != on-chain {on_chain}")
        print(f"  {g['label']:6s} gauge {g['gauge']} OK")

    print("\n=== Checkpointing VotingEscrow ===")
    ve.checkpoint()

    print(f"\n=== Creating the gauge vote from {TEST_PROPOSER} ===")
    actions = build_vote_actions(comparator, gc)
    with boa.env.prank(TEST_PROPOSER):
        pid7 = voting.createProposal(*Proposal(
            metadata=b"", actions=actions, allowFailureMap=0,
            startDate=0, endDate=0, voteOption=0, tryEarlyExecution=True))
    print(f"  created proposal {pid7}")

    print("\n=== Passing and executing the gauge vote ===")
    pass_vote(voting, pid7)
    boa.env.time_travel(seconds=voting.minDuration() + 3600)
    assert voting.canExecute(pid7), "gauge vote cannot execute"
    voting.execute(pid7)

    print("\n=== Result: GaugeController state ===")
    ok = True
    for g in GAUGES:
        added = gc.time_weight(g["gauge"]) != 0
        ok &= added
        print(f"  {g['label']:6s} {g['gauge']}  "
              f"{'REGISTERED' if added else 'MISSING'}")
    print("\n" + ("ALL 4 GAUGES REGISTERED - vote works end-to-end."
                  if ok else "FAILED - some gauges not registered."))


def run_prod():
    if not PROD_PROPOSER_KEYSTORE:
        sys.exit("Set PROD_PROPOSER_KEYSTORE to the hot-wallet keystore name.")
    boa.set_network_env(NETWORK)
    boa.env.add_account(account_load(PROD_PROPOSER_KEYSTORE), force_eoa=True)
    factory, comparator, gc, voting, ve = load_contracts()

    print("=== Checkpointing VotingEscrow ===")
    ve.checkpoint()

    print("=== Creating the gauge vote ===")
    pid = voting.createProposal(*Proposal(
        metadata=pin_to_ipfs(vote_metadata()).encode(),
        actions=build_vote_actions(comparator, gc), allowFailureMap=0,
        startDate=0, endDate=0, voteOption=0, tryEarlyExecution=True))
    print(f"Created proposal: {pid}")


if __name__ == "__main__":
    if "--test" in sys.argv[1:]:
        run_test()
    else:
        run_prod()
