#!/usr/bin/env python3
"""
Deploy a fresh LTMigrator wired to the CURRENT Factory owner and create a YB
DAO vote that registers it as a limit setter on that owner while disabling the
stale-owner migrator BROKEN_LT_MIGRATOR.

Why this is needed
------------------
The currently-registered migrator BROKEN_LT_MIGRATOR (0xE707...) was deployed
with its immutable FACTORY_OWNER pointing at a now-stale HybridFactoryOwner
(0x0f4e...). The Factory admin has since moved to the new/fixed owner
(0xb8BA...). When the migrator routes lt_allocate_stablecoins through the stale
owner, the LT's _check_admin only accepts the *current* Factory admin, so every
migration reverts "Access" (reproduced in tests_forked/test_migrator_access.py).

FACTORY_OWNER is immutable, so the migrator cannot be repaired in place -- it
must be redeployed against the current owner. Registering the redeploy as a
limit setter is ADMIN-only on the owner, and that ADMIN is the DAO Ownership
agent, so this step REQUIRES A DAO VOTE. Both the enable (new) and disable
(broken) happen inside one proposal so the swap is atomic.

Usage:
  python scripts/voting/create_vote_redeploy_migrator_owner.py          # prod
  python scripts/voting/create_vote_redeploy_migrator_owner.py --test   # fork

--test forks mainnet at head, deploys the new migrator, creates this swap
proposal, passes + executes it via the test whales, asserts the limit_setters
mapping flipped, and then runs the actual reported user migration
(0xD24C... : LT 0xfBF3... -> 0x651D...) end-to-end to prove it now succeeds.
"""
import json
import os
import sys
from collections import namedtuple
from getpass import getpass
from time import sleep

import boa
import requests
from eth_account import account
from eth_utils import to_checksum_address

from boa.explorer import Etherscan
from boa.verifiers import verify as boa_verify

from networks import NETWORK, PINATA_TOKEN, ETHERSCAN_API_KEY

VOTING_PLUGIN = "0x2be6670DE1cCEC715bDBBa2e3A6C1A05E496ec78"
YB_FACTORY = "0x370a449FeBb9411c95bf897021377fe0B7D100c0"

# The migrator this script retires. Registered as a limit_setter on the current
# owner (0xb8BA...) but wired (immutable FACTORY_OWNER) to the stale owner
# 0x0f4e..., so it reverts "Access" on every migration. See
# tests_forked/test_migrator_access.py for the in-fork traceback.
BROKEN_LT_MIGRATOR = "0xE707c7a9dD58fb7eEa17acFF875CEF8d10eD1a9F"

# Brownie keystore for the proposer EOA. TokenVoting enforces a 1-day
# per-address createProposal cooldown, so this needs to be an account whose
# last Aragon proposal is at least 24h old.
PROPOSER_KEYSTORE = "yb-deployer-2"

# The reported stuck migration -- used by --test to prove the fix end-to-end.
REPORT_USER = "0xD24C29f58fA7F57fb70EBb059B1ffd795E23800e"
REPORT_LT_FROM = "0xfBF3C16676055776Ab9B286492D8f13e30e2E763"
REPORT_LT_TO = "0x651D4b8168488FA163D85304662E8278d4c55BAa"

# Largest veYB voters -- forked dry-run only. Generated by
# scripts/voting/find_ve_voters.py (top 25, ~75% of veYB power).
TEST_VOTERS = [
    "0xD10782f4D4fE20f5E15f3347E5D59aB3eC6D63d6",
    "0xb75BB762e5D62ca8f23FAbC87b1f651d0171d521",
    "0x0070D9adC687a28FBAcC0a0Aab24B90c037AD24e",
    "0x0000000C90799449af8eE0B240Da639144a36C6A",
    "0x29B6a3512FafeAce91433D278503ABC3D5aB5d12",
    "0x64A0f7Ca6efbFDaF975B5127650EC9f175182d7b",
    "0x2DE99955fA0318556f3542E71421EFD1BCF3293a",
    "0xc64566f526F09eEeFbd284760D0E1b94c6e69fc8",
    "0xb373e9C6D3Ad91eD03AA4b3C8106e68Bf3de192f",
    "0xC2059e0F6C4c1D441BAf295BC6Ea15cE24c71701",
    "0x2029Df02833eb9cd83A5143AbfE5d65BC4B46A16",
    "0xEeee8f503bCF020bc0909D35FBAbEe9ffD24641a",
    "0xaE922Cea2323fD75a31e28d10E0c84F49e1Fb6b7",
    "0xc900C3EFDC7d790f50b0B43b0c4206F8141a77eC",
    "0x52658B966801D8ddB6f49c886557084EC459Aa27",
    "0x53F8Ef5B139824C85d3f837C6b535470bFBFEeE3",
    "0xfF642740228d6abe9786612A421C0B1b859f0793",
    "0x0ca0e5c9f426d1e3EF1f568862716c68b1f44a01",
    "0x9cB95F0Fa3dB70eb15D1505d3c73a55766A1Ec89",
    "0x387ACB7f56A6f29137a21d7Eb755A3F638cab45B",
    "0x3340a1541296E7A4db2Ac6f9C3776bda7eF62724",
    "0xF791da446D04282f921f38FBF954aD5cAee899a3",
    "0x27c6DCcF18d6e66942dc5a250B1618B6B3A44036",
    "0x858a2FEf6C0833f8a5532122bb964655b0E6d5B5",
    "0x1105c075A4034C57d1457151b2D7cAb2ed99B122",
]

VOTE_YES = 2
VERIFY_RETRY_SECONDS = 10

Proposal = namedtuple(
    "Proposal",
    ["metadata", "actions", "allowFailureMap", "startDate", "endDate",
     "voteOption", "tryEarlyExecution"],
)
Action = namedtuple("Action", ["to", "value", "data"])
ABI_DIR = os.path.dirname(os.path.abspath(__file__))


# --- keystore helpers --------------------------------------------------------

def _keystore_path(name: str) -> str:
    return os.path.expanduser(
        os.path.join("~", ".brownie", "accounts", name + ".json"))


def keystore_address(name: str) -> str:
    with open(_keystore_path(name)) as f:
        return to_checksum_address("0x" + json.load(f)["address"])


def account_load(name: str):
    with open(_keystore_path(name)) as f:
        pkey = account.decode_keyfile_json(json.load(f), getpass())
    return account.Account.from_key(pkey)


# --- contract handles --------------------------------------------------------

def load_contracts():
    factory = boa.load_partial("contracts/Factory.vy").at(YB_FACTORY)
    # The migrator MUST be wired to the live Factory admin, whatever it is now.
    factory_owner = boa.load_partial("contracts/HybridFactoryOwner.vy").at(
        factory.admin())
    voting = boa.load_abi(
        os.path.join(ABI_DIR, "TokenVoting.abi.json"), name="AragonVoting"
    ).at(VOTING_PLUGIN)
    ve = boa.load_partial("contracts/dao/VotingEscrow.vy").at(
        voting.getVotingToken())
    return factory, factory_owner, voting, ve


# --- forked-test: passing + executing a vote ---------------------------------

def pass_vote(voting, pid: int):
    cast = 0
    for voter in TEST_VOTERS:
        if voting.isMinParticipationReached(pid):
            break
        if not voting.canVote(pid, voter, VOTE_YES):
            continue
        with boa.env.prank(voter):
            voting.vote(pid, VOTE_YES, False)
        cast += 1
    if not voting.isMinParticipationReached(pid):
        raise RuntimeError(f"Proposal {pid} did not reach quorum "
                           f"({cast} whales voted)")
    print(f"    {cast} whale(s) voted YES; quorum reached")


# --- the swap vote -----------------------------------------------------------

def build_vote_actions(factory_owner, new_migrator: str) -> list:
    return [
        Action(to=factory_owner.address, value=0,
               data=factory_owner.set_limit_setter.prepare_calldata(
                   new_migrator, True)),
        Action(to=factory_owner.address, value=0,
               data=factory_owner.set_limit_setter.prepare_calldata(
                   BROKEN_LT_MIGRATOR, False)),
    ]


def vote_metadata(new_migrator: str, factory_owner: str) -> dict:
    return {
        "title": "YB v3: redeploy LTMigrator against the current Factory owner",
        "summary": (
            f"Register the new LTMigrator {new_migrator} (wired to the current "
            f"Factory owner {factory_owner}) as a limit setter on that owner, "
            f"and disable the stale migrator {BROKEN_LT_MIGRATOR}. The stale "
            "migrator's immutable FACTORY_OWNER points at the previous owner "
            "(0x0f4e...), which is no longer the Factory admin, so every "
            "migration through it reverts 'Access' when the LT's _check_admin "
            "rejects the stale owner. FACTORY_OWNER is immutable, so the only "
            "fix is to redeploy against the current owner and re-point the "
            "limit-setter registration."
        ),
        "resources": [],
    }


# --- IPFS / Etherscan --------------------------------------------------------

def pin_to_ipfs(content: dict) -> str:
    response = requests.post(
        "https://api.pinata.cloud/pinning/pinJSONToIPFS",
        json={"pinataContent": content,
              "pinataMetadata": {"name": "pinnie.json"},
              "pinataOptions": {"cidVersion": 1}},
        headers={"Authorization": f"Bearer {PINATA_TOKEN}",
                 "Content-Type": "application/json"},
        timeout=30,
    )
    assert 200 <= response.status_code < 400, response.text
    return "ipfs://" + response.json()["IpfsHash"]


def verify_on_etherscan(contract, etherscan):
    while True:
        try:
            sleep(VERIFY_RETRY_SECONDS)
            boa_verify(contract, etherscan, wait=True)
            return
        except ValueError as e:
            print(e)
            if "Already Verified" in str(e):
                return


# --- entrypoints -------------------------------------------------------------

def run_test():
    boa.fork(NETWORK, block_identifier="latest")
    factory, factory_owner, voting, ve = load_contracts()
    print(f"  current Factory owner: {factory_owner.address}")
    assert factory_owner.limit_setters(BROKEN_LT_MIGRATOR), (
        f"{BROKEN_LT_MIGRATOR} is not a limit_setter on the current owner — "
        "hardcoded address/state is wrong?")

    print("\n=== Deploying new LTMigrator ===")
    new_migrator = boa.load(
        "contracts/LTMigrator.vy", factory.STABLECOIN(),
        factory_owner.address)
    assert new_migrator.FACTORY_OWNER().lower() == factory_owner.address.lower()
    print(f"  new migrator: {new_migrator.address}")

    print("\n=== Checkpointing VotingEscrow ===")
    ve.checkpoint()

    proposer = keystore_address(PROPOSER_KEYSTORE)
    print(f"\n=== Creating the swap vote from {PROPOSER_KEYSTORE} "
          f"({proposer}) ===")
    actions = build_vote_actions(factory_owner, new_migrator.address)
    with boa.env.prank(proposer):
        pid = voting.createProposal(*Proposal(
            metadata=b"", actions=actions, allowFailureMap=0,
            startDate=0, endDate=0, voteOption=0, tryEarlyExecution=True))
    print(f"  created proposal {pid}")

    print("\n=== Passing and executing the swap vote ===")
    pass_vote(voting, pid)
    boa.env.time_travel(seconds=voting.minDuration() + 3600)
    assert voting.canExecute(pid), "swap vote cannot execute"
    voting.execute(pid)

    print("\n=== Post-execution state ===")
    new_is = factory_owner.limit_setters(new_migrator.address)
    broken_is = factory_owner.limit_setters(BROKEN_LT_MIGRATOR)
    print(f"  limit_setters[new    {new_migrator.address}] = {new_is}")
    print(f"  limit_setters[broken {BROKEN_LT_MIGRATOR}] = {broken_is}")
    assert new_is and not broken_is, "swap state mismatch"

    print("\n=== Running the reported user migration end-to-end ===")
    lt_from = boa.load_partial("contracts/LT.vy").at(REPORT_LT_FROM)
    shares = lt_from.balanceOf(REPORT_USER)
    assert shares > 0, "reported user has no lt_from balance"
    with boa.env.prank(REPORT_USER):
        lt_from.approve(new_migrator.address, 2**256 - 1)
        out = new_migrator.migrate_plain(REPORT_LT_FROM, REPORT_LT_TO, shares, 0)
    assert lt_from.balanceOf(REPORT_USER) == 0
    print(f"  migrated {shares} lt_from -> received lt_to (shares_out={out})")
    print("\nMigrator redeploy + swap works end-to-end.")


def run_prod():
    boa.set_network_env(NETWORK)
    boa.env.add_account(account_load(PROPOSER_KEYSTORE), force_eoa=True)
    factory, factory_owner, voting, ve = load_contracts()
    print(f"  current Factory owner: {factory_owner.address}")

    etherscan = Etherscan(api_key=ETHERSCAN_API_KEY)
    print("=== Deploying new LTMigrator ===")
    new_migrator = boa.load(
        "contracts/LTMigrator.vy", factory.STABLECOIN(),
        factory_owner.address)
    print(f"  new migrator: {new_migrator.address}")

    print(f"\n=== Verifying {new_migrator.address} on Etherscan ===")
    verify_on_etherscan(new_migrator, etherscan)
    print("  verified")

    print("\n=== Checkpointing VotingEscrow ===")
    ve.checkpoint()

    print("=== Creating the swap vote ===")
    metadata = pin_to_ipfs(
        vote_metadata(new_migrator.address, factory_owner.address)).encode()
    pid = voting.createProposal(*Proposal(
        metadata=metadata,
        actions=build_vote_actions(factory_owner, new_migrator.address),
        allowFailureMap=0,
        startDate=0, endDate=0, voteOption=0, tryEarlyExecution=True))
    print(f"Created proposal: {pid}")


if __name__ == "__main__":
    if "--test" in sys.argv[1:]:
        run_test()
    else:
        run_prod()
